"""Add RBAC tables and hierarchical roles

Revision ID: 2008b7b7815e
Revises: 2242e527ac00
Create Date: 2025-08-06 11:23:10.053649

"""

# revision identifiers, used by Alembic.
revision = "2008b7b7815e"
down_revision = "add_folder_structure"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # All RBAC tables and fields are now created in the initial migration
    # This migration is kept for compatibility but does nothing
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # All RBAC tables and fields are now created in the initial migration
    # This migration is kept for compatibility but does nothing
    pass
    # ### end Alembic commands ###
