"""Update role model schema to match expected structure

Revision ID: e516f23850a2
Revises: e7d0b31d2cd3
Create Date: 2025-08-06 11:33:58.395698

"""

# revision identifiers, used by Alembic.
revision = "e516f23850a2"
down_revision = "e7d0b31d2cd3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # All role schema updates are now included in the initial migration
    # This migration is kept for compatibility but does nothing
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # All role schema updates are now included in the initial migration
    # This migration is kept for compatibility but does nothing
    pass
    # ### end Alembic commands ###
