"""Fix RBAC relationships and add missing fields

Revision ID: e7d0b31d2cd3
Revises: 2008b7b7815e
Create Date: 2025-08-06 11:32:13.076902

"""

# revision identifiers, used by Alembic.
revision = "e7d0b31d2cd3"
down_revision = "2008b7b7815e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # All RBAC fields are now created in the initial migration
    # This migration is kept for compatibility but does nothing
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # All RBAC fields are now created in the initial migration
    # This migration is kept for compatibility but does nothing
    pass
    # ### end Alembic commands ###
